feat: add terradoc
mineiros-io/terraform-google-network-vpc pull request #11
Opened 2021-12-09 23:11 UTC by kassianh

Recreated README with terradoc, checked documentation for errors or inconsistencies.

2021-12-10 15:08 UTC, mariux requested changes

2021-12-10 15:08 UTC, mariux commented on Makefile
> +rm-command    = $(call quiet-command,rm -rf ${1},"${YELLOW}[CLEAN] ${GREEN}${1}${RESET}")
please add EOL at EOF... this can be fixed in you editor settings to always follow this.

why do you add go-test command that is not used in the Makefile?

2021-12-10 15:14 UTC, mariux requested changes

2021-12-10 15:14 UTC, mariux commented on README.md
> +
trailing spaces should not be added but be always removed.

2021-12-10 15:14 UTC, mariux commented on README.md
> +    ]
this indent change is wrong.

2021-12-10 15:14 UTC, mariux commented on README.tfdoc.hcl
> +              ]
```suggestion
              google_project.project_id
            ]
```

2021-12-10 15:14 UTC, mariux commented on README.tfdoc.hcl
> +        The outputs of the created VPC.
@thiesen can you create a ticket for also supporting outputs?

2021-12-10 15:14 UTC, mariux commented on README.tfdoc.hcl
> +      Copyright &copy; 2020-2021 [Mineiros GmbH][homepage]
```suggestion
      Copyright &copy; 2020-2022 [Mineiros GmbH][homepage]
```

2021-12-10 15:14 UTC, mariux commented on README.tfdoc.hcl
> +    title   = "Module Attributes Reference"
maybe we should rename this to `Module Outputs` which is way more common? 

wdyt @soerenmartius @kassianh @thiesen @Hanymin

2021-12-10 15:14 UTC, mariux commented on README.tfdoc.hcl
> +    title   = "Module Attributes Reference"
if accpeted please prepare a PR in template first ;)

2021-12-10 15:14 UTC, mariux commented on README.md
> +
@thiesen is this an issue in the renderer?

2021-12-12 20:25 UTC, kassianh commented on Makefile
> +rm-command    = $(call quiet-command,rm -rf ${1},"${YELLOW}[CLEAN] ${GREEN}${1}${RESET}")
Changed the editor settings, thanks. I edited it because that's what's in the Makefile in the terraform-module-template

2021-12-12 21:21 UTC, kassianh commented on README.md
> +
Nope, issue with readme2tfdoc

2021-12-12 21:56 UTC, kassianh commented on README.tfdoc.hcl
> +      Copyright &copy; 2020-2021 [Mineiros GmbH][homepage]
Changed in new commit.

2021-12-14 00:30 UTC, soerenmartius submitted a review, later dismissed

2021-12-14 00:30 UTC, soerenmartius commented on README.tfdoc.hcl
> +  url   = "https://mineiros.io/?ref=terraform-module-template"
```suggestion
  url   = "https://mineiros.io/?ref=terraform-google-network-vpc"
```

2021-12-14 00:30 UTC, soerenmartius commented on README.tfdoc.hcl
> +    image = "https://github.com/mineiros-io/terraform-module-template/workflows/Tests/badge.svg"
```suggestion
    image = "https://github.com/mineiros-io/terraform-google-network-vpc/workflows/Tests/badge.svg"
```

2021-12-14 00:30 UTC, soerenmartius commented on README.tfdoc.hcl
> +    url   = "https://github.com/mineiros-io/terraform-module-template/actions"
```suggestion
    url   = "https://github.com/mineiros-io/terraform-google-network-vpc/actions"
```

2021-12-14 00:30 UTC, soerenmartius commented on README.tfdoc.hcl
> +    image = "https://img.shields.io/github/v/tag/mineiros-io/terraform-module-template.svg?label=latest&sort=semver"
```suggestion
    image = "https://img.shields.io/github/v/tag/mineiros-io/terraform-google-network-vpc.svg?label=latest&sort=semver"
```

2021-12-14 00:30 UTC, soerenmartius commented on README.tfdoc.hcl
> +    url   = "https://github.com/mineiros-io/terraform-module-template/releases"
```suggestion
    url   = "https://github.com/mineiros-io/terraform-google-network-vpc/releases"
```

2021-12-14 00:30 UTC, soerenmartius commented on README.tfdoc.hcl
> +    value = "https://img.shields.io/github/v/tag/mineiros-io/terraform-module-template.svg?label=latest&sort=semver"
```suggestion
    value = "https://img.shields.io/github/v/tag/mineiros-io/terraform-google-network-vpc.svg?label=latest&sort=semver"
```

2021-12-14 00:30 UTC, soerenmartius commented on README.md
> +[![Build Status](https://github.com/mineiros-io/terraform-module-template/workflows/Tests/badge.svg)](https://github.com/mineiros-io/terraform-module-template/actions)
```suggestion
[![Build Status](https://github.com/mineiros-io/terraform-google-network-vpc/workflows/Tests/badge.svg)](https://github.com/mineiros-io/terraform-google-network-vpc/actions)
```

2021-12-14 00:30 UTC, soerenmartius commented on README.md
> +[![GitHub tag (latest SemVer)](https://img.shields.io/github/v/tag/mineiros-io/terraform-module-template.svg?label=latest&sort=semver)](https://github.com/mineiros-io/terraform-module-template/releas
```suggestion
[![GitHub tag (latest SemVer)](https://img.shields.io/github/v/tag/mineiros-io/terraform-google-network-vpc.svg?label=latest&sort=semver)](https://github.com/mineiros-io/terraform-google-network-vpc/releases)
```

2021-12-14 15:27 UTC, thiesen commented on README.tfdoc.hcl
> +        The outputs of the created VPC.
sorry for the delay in getting back on this! I had a story for it already: https://app.shortcut.com/mineiros/story/4140/add-output-block

2021-12-14 15:28 UTC, thiesen commented on README.tfdoc.hcl
> +    title   = "Module Attributes Reference"
+1 for `Module Outputs`! (sorry for the delay - getting better with GH notifications now :sweat_smile: )

2021-12-15 11:38 UTC, i4ki approved these changes
lgtm but dont take this too seriously ;-)

2021-12-15 11:38 UTC, i4ki commented on README.md
>  #### Extended Resource Configuration
does it make sense to have empty sections?

2021-12-15 19:55 UTC, kassianh commented on README.md
>  #### Extended Resource Configuration
Good point, removed the empty section.

2021-12-15 21:07 UTC, mariux commented on README.tfdoc.hcl
> +    title   = "Module Attributes Reference"
Will change in template...

2021-12-15 21:11 UTC, mariux requested changes

2021-12-15 21:11 UTC, mariux commented on README.tfdoc.hcl
> +        - https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network
those should be subsections according to the template. please convert to subsections..

2021-12-15 21:11 UTC, mariux commented on README.tfdoc.hcl
> +    title   = "Module Attributes Reference"
@kassianh please already rename pr in template is open.

2021-12-15 21:30 UTC, kassianh commented on README.tfdoc.hcl
> +    title   = "Module Attributes Reference"
Done.

2021-12-15 21:33 UTC, kassianh commented on README.tfdoc.hcl
> +        - https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network
Done.

2021-12-16 15:06 UTC, thiesen approved these changes
lgtm

2021-12-16 23:11 UTC, mariux approved these changes

2021-12-16 23:11 UTC, merged