feat!: add new variables
mineiros-io/terraform-google-network-vpc pull request #18
Opened 2022-11-04 16:52 UTC by waxb

- chore: changelog updated
- feat!: add new variables

2022-11-04 19:28 UTC, soerenmartius requested changes
Corrected some typos (probably copy & paste from the already messed up Google docs) and added formatting for the README.

2022-11-04 19:28 UTC, soerenmartius commented on README.tfdoc.hcl
> +            Enable ULA internal ipv6 on this network. Enabling this feature will assign a /48 from google defined ULA prefix fd20::/20.
```suggestion
            Enable ULA internal ipv6 on this network. Enabling this feature will assign a `/48` from Google defined ULA prefix `fd20::/20`.
```

2022-11-04 19:28 UTC, soerenmartius commented on README.tfdoc.hcl
> +            When enabling ula internal ipv6, caller optionally can specify the /48 range they want from the google defined ULA prefix fd20::/20. The input must be a valid /48 ULA IPv6 address and mus
```suggestion
            When enabling ula internal ipv6, caller optionally can specify the `/48` range they want from the Google defined ULA prefix `fd20::/20`. The input must be a valid `/48` ULA IPv6 address and within the `fd20::/20`. The operation will fail if the specified `/48` is already in use by another resource. If the field is not specified, then a `/48` range will be randomly allocated from `fd20::/20` and returned via this field."
```

2022-11-05 15:37 UTC, soerenmartius approved these changes
lgtm! thanks. 

Maybe consider adding the new values to the complete test

2022-11-05 15:38 UTC, waxb commented
> lgtm! thanks.
> 
> Maybe consider adding the new values to the complete test

they were already

<img width="718" alt="Screenshot 2022-11-05 at 16 37 55" src="https://user-images.githubusercontent.com/10109428/200127902-a0e6b557-f200-4be9-babb-073a47ce512c.png">

thank you for the review!

2022-11-05 15:40 UTC, merged